export const COURSES_FETCHED = "COURSES_FETCHED";
export const COURSES_EMPTY = "COURSES_EMPTY";
export const COURSES_INCREMENT = "COURSES_INCREMENT";

export const COURSE_FETCHED = "COURSE_FETCHED";
export const COURSE_EMPTY = "COURSE_EMPTY";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";